version: '3.3'

services:
  db:
    image: mysql:8.0
    container_name: 1_db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - '3306:3306'
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASS}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: 1_phpmyadmin
    ports:
      - '81:80'
    expose:
      - 8080
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword

  apache:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 1_apache
    volumes:
      - "./website:/var/www/website"
    ports:
      - '80:80'

volumes:
  db_data: